modLoader="javafml"
loaderVersion="[46,)"
license="All Rights Reserved"

[[mods]]
modId="puffish_skill_leveling"
version="${version}"
displayName="Pufferfish Skill Leveling"
authors="DeveloperNoShinigami"
description="An addon for Pufferfish Skills that adds multi-level skill progression and per-level rewards."

[[dependencies.puffish_skill_leveling]]
modId="forge"
mandatory=true
versionRange="[46,)"
ordering="NONE"
side="BOTH"

[[dependencies.puffish_skill_leveling]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"
side="BOTH"

[[dependencies.puffish_skill_leveling]]
modId="puffish_skills"
mandatory=true
versionRange="[0.17,)"
ordering="AFTER"
side="BOTH"

[[dependencies.puffish_skill_leveling]]
modId="curios"
mandatory=false
versionRange="[5.14,)"
ordering="AFTER"
side="BOTH"
